### ISSUE TITLE
successful but no files processed

### ISSUE THREAD

**Issue by tibo2t** [DRCRecoveryData/CR2-Repair-Tool#1]
Hello, 
When i launch CR2-Repair-Tool, i select the reference file and workdir but no files processed.
The repaired directory is empty.
![image](https://github.com/user-attachments/assets/ed107ca6-29de-4a56-8a4f-bea3caf6e3a4)

However, my images have corrupted metadata: 
![image](https://github.com/user-attachments/assets/e52c9978-8ba4-466b-854a-077b1b26140f)
Only the last one image is corrupted.

**Comment by DRCRecoveryData** [comment]
> Hello, 
> When i launch CR2-Repair-Tool, i select the reference file and workdir but no files processed.
> The repaired directory is empty.
> ![image](https://github.com/user-attachments/assets/ed107ca6-29de-4a56-8a4f-bea3caf6e3a4)
> 
> However, my images have corrupted metadata: 
> ![image](https://github.com/user-attachments/assets/e52c9978-8ba4-466b-854a-077b1b26140f)
> Only the last one image is corrupted.
> 

Hi,

I have made repair ransomware files, you should rename corrupt files from .CR2 to CR2.xxxx

Also make sure the reference file is taken from the same camera of corrupted

Corrupted only work when have FF D8 FF C4 signature when found in hex dump

**Comment by DRCRecoveryData** [comment]
Try my new update committed

**Comment by tibo2t** [comment]
Thank you for your help!
The program crash when he processed a corrupted file;

![image](https://github.com/user-attachments/assets/2acb3817-c1b3-491b-ab3d-48132468e3ff)

When i rename a corrupted file CR2 to CR2.xxx : 

![image](https://github.com/user-attachments/assets/c29de63f-a734-43e9-8559-c4706a4e3075)

It's very strange the images come from the same camera, but a large part of my images are unreadable and this seems to come from the metadata.
For example when I do: file corrupted_file 
I get a data file instead of Canon CR2 raw image data, version 2.0

**Comment by DRCRecoveryData** [comment]
> Thank you for your help! The program crash when he processed a corrupted file;
> 
> ![image](https://private-user-images.githubusercontent.com/155970326/382110767-2acb3817-c1b3-491b-ab3d-48132468e3ff.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA2MDM1NDEsIm5iZiI6MTczMDYwMzI0MSwicGF0aCI6Ii8xNTU5NzAzMjYvMzgyMTEwNzY3LTJhY2IzODE3LWMxYjMtNDkxYi1hYjNkLTQ4MTMyNDY4ZTNmZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEwM1QwMzA3MjFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lODI1ZDhjY2JhZmMwNTAzOTZiMWVhZjBhZTAzMDJmNDk5MDM5YTQ4M2RmOWY2MDgwY2EzNTA1ZDFmODc3NDBlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.uOMHMsPoT7xpjfTB-abU_u1vHogwfGfKD53jmrmNHFk)
> 
> When i rename a corrupted file CR2 to CR2.xxx :
> 
> ![image](https://private-user-images.githubusercontent.com/155970326/382112377-c29de63f-a734-43e9-8559-c4706a4e3075.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA2MDM1NDEsIm5iZiI6MTczMDYwMzI0MSwicGF0aCI6Ii8xNTU5NzAzMjYvMzgyMTEyMzc3LWMyOWRlNjNmLWE3MzQtNDNlOS04NTU5LWM0NzA2YTRlMzA3NS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEwM1QwMzA3MjFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02ZjcwZTlmMzlkMjA3ZGY0YzIzOTE5ZjlmY2IyNjJkMWEwMjM0ZWJhZGE1M2UyOTBlNmZiNTBiZWJhMzhhZWFiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.0f4ZUeidUhm6rnmAbGPzqTkiTW8S0HE720Dhm5ywkmM)
> 
> It's very strange the images come from the same camera, but a large part of my images are unreadable and this seems to come from the metadata. For example when I do: file corrupted_file I get a data file instead of Canon CR2 raw image data, version 2.0

Can you upload your 5-10 file corrupted and 1-2 rerference file?

**Comment by tibo2t** [comment]
Hello, 

Sorry for the delay. 
The photos are relatively confidential, can you tell me how to solve the problem of corrupted photos? 
I'm also interested in any documentation on the CR2 format.

**Comment by DRCRecoveryData** [comment]
> Hello, 
> 
> 
> 
> Sorry for the delay. 
> 
> The photos are relatively confidential, can you tell me how to solve the problem of corrupted photos? 
> 
> I'm also interested in any documentation on the CR2 format.

what happen with your jpeg files?

**Comment by tibo2t** [comment]
It's raw files (CR2 format) taken with a Canon camera. 
I tried to convert my corrupted cr2 files to jpeg but it doesn't work.

My files are simply not openable, in I do the command : file MY_IMAGE_CORROMPU . 
My terminal tells me that the file is of type data when it should indicate CR2 file. 

![image](https://github.com/user-attachments/assets/daa780c3-32fa-4856-a192-f24250d63195)
![image](https://github.com/user-attachments/assets/cbff82d7-0b93-44d1-837c-000b4bc16584)
