### ISSUE TITLE
IndentationError

### ISSUE THREAD

**Issue by TheUser1992** [DRCRecoveryData/CR2-Repair-Tool#2]
File "D:\Software\CR2-Repair-Tool-main\cr2repair-gui.py", line 23
    repaired_folder_path = os.path.join(self.encrypted_folder_path, "Repaired")
    ^
IndentationError: expected an indented block after function definition on line 21

**Comment by DRCRecoveryData** [comment]
Hi,
Fixed, use lastest commit
